Models/BioSamples.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

// Code scaffolded by EF Core assumes nullable reference types (NRTs) are not used or disabled.
// If you have enabled NRTs for your project, then un-comment the following line:
// #nullable disable

namespace Intex
{
    //create the BioSamples class to hold DB information
    public partial class BioSamples
    {
        [Key]
        public int BioSampleId { get; set; }
        public double? RackNumber { get; set; }
        public string BagNumber { get; set; }
        public double? LowPairNs { get; set; }
        public double? HighPairNs { get; set; }
        public string BurialLocationNs { get; set; }
        public double? LowPairEw { get; set; }
        public double? HighPairEw { get; set; }
        public string BurialLocationEw { get; set; }
        public string BurialSubplot { get; set; }
        public double? BurialNumber { get; set; }
        public double? Date { get; set; }
        public string PreviouslySampled { get; set; }
        public string Notes { get; set; }
        public string Initials { get; set; }
        public int? BurialId { get; set; }

        public virtual Burials Burial { get; set; }
    }
}

Controllers/BioSamplesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Intex;
using Intex.Models;
using Intex.ViewModels;
using Microsoft.AspNetCore.Authorization;

namespace Intex.Controllers
{
    //lock down controller so only admins and researchers can access MOST actions.
    //other actions can be unlocked by adding the "AllowAnonymous" tag helper
    [Authorize(Roles = "Admin,Researcher")]
    public class BioSamplesController : Controller
    {
        private readonly BioSamplesDbContext _context;

        //add in the context file
        public BioSamplesController(BioSamplesDbContext context)
        {
            _context = context;
        }

        //unlock the index page for anonymous users
        //include pagination
        [AllowAnonymous]
        public IActionResult Index(int pageNum = 1)
        {
            int pageSize = 10;

            //create a new index view model to handle the DBSet and pagination
            return View(new IndexViewModel
            {
                BioSamples = _context.BioSamples
                    .Skip((pageNum - 1) * pageSize)
                    .Take(pageSize)
                    .ToList(),

                PagingInfo = new PagingInfo
                {
                    CurrentPage = pageNum,
                    ItemsPerPage = pageSize,
                    TotalNumItems = (_context.BioSamples.Count())
                },
            });
        }

        //Page to filter by ALL data in a database
        [AllowAnonymous]
        public IActionResult AllData()
        {
            return View(_context.BioSamples);
        }


        // GET: BioSamples/Details/5
        [AllowAnonymous]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bioSamples = await _context.BioSamples
                .Include(b => b.Burial)
                .FirstOrDefaultAsync(m => m.BioSampleId == id);
            if (bioSamples == null)
            {
                return NotFound();
            }

            return View(bioSamples);
        }

        // GET: BioSamples/Create
        public IActionResult Create()
        {
            ViewData["BurialId"] = new SelectList(_context.Set<Burials>(), "BurialId", "BurialId");
            return View();
        }

        // POST: BioSamples/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BioSampleId,RackNumber,BagNumber,LowPairNs,HighPairNs,BurialLocationNs,LowPairEw,HighPairEw,BurialLocationEw,BurialSubplot,BurialNumber,Date,PreviouslySampled,Notes,Initials,BurialId")] BioSamples bioSamples)
        {
            if (ModelState.IsValid)
            {
                _context.Add(bioSamples);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["BurialId"] = new SelectList(_context.Set<Burials>(), "BurialId", "BurialId", bioSamples.BurialId);
            return View(bioSamples);
        }

        // GET: BioSamples/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bioSamples = await _context.BioSamples.FindAsync(id);
            if (bioSamples == null)
            {
                return NotFound();
            }
            ViewData["BurialId"] = new SelectList(_context.Set<Burials>(), "BurialId", "BurialId", bioSamples.BurialId);
            return View(bioSamples);
        }

        // POST: BioSamples/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("BioSampleId,RackNumber,BagNumber,LowPairNs,HighPairNs,BurialLocationNs,LowPairEw,HighPairEw,BurialLocationEw,BurialSubplot,BurialNumber,Date,PreviouslySampled,Notes,Initials,BurialId")] BioSamples bioSamples)
        {
            if (id != bioSamples.BioSampleId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(bioSamples);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BioSamplesExists(bioSamples.BioSampleId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["BurialId"] = new SelectList(_context.Set<Burials>(), "BurialId", "BurialId", bioSamples.BurialId);
            return View(bioSamples);
        }

        // GET: BioSamples/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bioSamples = await _context.BioSamples
                .Include(b => b.Burial)
                .FirstOrDefaultAsync(m => m.BioSampleId == id);
            if (bioSamples == null)
            {
                return NotFound();
            }

            return View(bioSamples);
        }

        // POST: BioSamples/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var bioSamples = await _context.BioSamples.FindAsync(id);
            _context.BioSamples.Remove(bioSamples);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BioSamplesExists(int id)
        {
            return _context.BioSamples.Any(e => e.BioSampleId == id);
        }
    }
}

Views/BioSamples/AllData.cshtml
@model IEnumerable<BioSamples>
@inject SignInManager<IdentityUser> signInManager;

@{
    ViewData["Title"] = "Bio Samples";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@*Show off all the data we can in this page*@

@*Will be injected into header to allow the filter to work*@
@section header{
    <script src="https://code.jquery.com/jquery-2.2.4.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            $("#demo").on("keyup", function () {
                var value = $(this).val().toLowerCase();
                $("#test tr").filter(function () {
                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
            });
        });
    </script>
}

<h1>Filter by ALL Bio Sample Data</h1>

@*Table with information*@
<div class="container">
    <input class="form-control" id="demo" type="text" placeholder="Enter your search term here...">
    <br>
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>
                    Rack Number
                </th>
                <th>
                    Burial Subplot
                </th>
                <th>
                    Burial Number
                </th>
                <th>
                    Date
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody id="test">
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.RackNumber)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.BurialSubplot)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.BurialNumber)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Date)
                    </td>
                    <td>
                        @if (signInManager.IsSignedIn(User) && (User.IsInRole("Admin") || (User.IsInRole("Researcher"))))
                        {
                            <a asp-action="Edit" asp-route-id="@item.BurialId" class="btn btn-secondary m-1" style="width: 80px">Edit</a>
                        }

                        <a asp-action="Details" asp-route-id="@item.BurialId" class="btn btn-brownsugar m-1" style="width: 80px">Details</a>
                        @if (signInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                        {
                            <a asp-action="Delete" asp-route-id="@item.BurialId" class="btn btn-cedarchest m-1" style="width: 80px">Delete</a>
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

Views/BioSamples/Create.cshtml
@model Intex.BioSamples

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@*Allow a researcher or admin to create a new entry*@

<h1>New BioSample Entry</h1>

@*form to allow creation of new entry*@
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="RackNumber" class="control-label"></label>
                <input asp-for="RackNumber" class="form-control" />
                <span asp-validation-for="RackNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BagNumber" class="control-label"></label>
                <input asp-for="BagNumber" class="form-control" />
                <span asp-validation-for="BagNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LowPairNs" class="control-label"></label>
                <input asp-for="LowPairNs" class="form-control" />
                <span asp-validation-for="LowPairNs" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HighPairNs" class="control-label"></label>
                <input asp-for="HighPairNs" class="form-control" />
                <span asp-validation-for="HighPairNs" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BurialLocationNs" class="control-label"></label>
                <input asp-for="BurialLocationNs" class="form-control" />
                <span asp-validation-for="BurialLocationNs" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LowPairEw" class="control-label"></label>
                <input asp-for="LowPairEw" class="form-control" />
                <span asp-validation-for="LowPairEw" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HighPairEw" class="control-label"></label>
                <input asp-for="HighPairEw" class="form-control" />
                <span asp-validation-for="HighPairEw" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BurialLocationEw" class="control-label"></label>
                <input asp-for="BurialLocationEw" class="form-control" />
                <span asp-validation-for="BurialLocationEw" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BurialSubplot" class="control-label"></label>
                <input asp-for="BurialSubplot" class="form-control" />
                <span asp-validation-for="BurialSubplot" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BurialNumber" class="control-label"></label>
                <input asp-for="BurialNumber" class="form-control" />
                <span asp-validation-for="BurialNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PreviouslySampled" class="control-label"></label>
                <input asp-for="PreviouslySampled" class="form-control" />
                <span asp-validation-for="PreviouslySampled" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Notes" class="control-label"></label>
                <input asp-for="Notes" class="form-control" />
                <span asp-validation-for="Notes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Initials" class="control-label"></label>
                <input asp-for="Initials" class="form-control" />
                <span asp-validation-for="Initials" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BurialId" class="control-label"></label>
                <select asp-for="BurialId" class ="form-control" asp-items="ViewBag.BurialId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Add Entry" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-secondary m-1">Discard Entry</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/BioSamples/Delete.cshtml
@model Intex.BioSamples

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Remove BioSample Entry</h1>

@*Confirmation page to allow an admin remove an entry from the database*@

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RackNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RackNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BagNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BagNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LowPairNs)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LowPairNs)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HighPairNs)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HighPairNs)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BurialLocationNs)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BurialLocationNs)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LowPairEw)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LowPairEw)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HighPairEw)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HighPairEw)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BurialLocationEw)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BurialLocationEw)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BurialSubplot)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BurialSubplot)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BurialNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BurialNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PreviouslySampled)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PreviouslySampled)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Notes)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Notes)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Initials)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Initials)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Burial)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Burial.BurialId)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="BioSampleId" />
        <input type="submit" value="Delete" class="btn btn-cedarchest" />
        <a asp-action="Index" class="btn btn-secondary m-1">Back to List</a>
    </form>
</div>

Views/BioSamples/Details.cshtml
@model Intex.BioSamples
@inject SignInManager<IdentityUser> signInManager;

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>BioSample Entry Details</h1>

@*Show all details for a selected entry*@

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-3">
            Rack Number
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.RackNumber)
        </dd>
        <dt class="col-sm-3">
           Bag Number
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.BagNumber)
        </dd>
        <dt class="col-sm-3">
            Low Pair North or South
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.LowPairNs)
        </dd>
        <dt class="col-sm-3">
            High Pair North or South
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.HighPairNs)
        </dd>
        <dt class="col-sm-3">
            Burial Location North or South
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.BurialLocationNs)
        </dd>
        <dt class="col-sm-3">
            Low Pair East or West
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.LowPairEw)
        </dd>
        <dt class="col-sm-3">
            High Pair East or West
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.HighPairEw)
        </dd>
        <dt class="col-sm-3">
            Burial Location East or West
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.BurialLocationEw)
        </dd>
        <dt class="col-sm-3">
            Burial Subplot
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.BurialSubplot)
        </dd>
        <dt class="col-sm-3">
            Burial Number
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.BurialNumber)
        </dd>
        <dt class="col-sm-3">
            Date
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class="col-sm-3">
            Previously Sampled
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.PreviouslySampled)
        </dd>
        <dt class="col-sm-3">
            Notes
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.Notes)
        </dd>
        <dt class="col-sm-3">
            Initials
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.Initials)
        </dd>
        <dt class="col-sm-3">
            Burial ID
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.Burial.BurialId)
        </dd>
    </dl>
</div>
<div>
    @if (signInManager.IsSignedIn(User) && (User.IsInRole("Admin") || (User.IsInRole("Researcher"))))
    {
        <a asp-action="Edit" asp-route-id="@Model.BioSampleId" class="btn btn-brownsugar m-1">Edit</a>

    }
    <a asp-action="Index" class="btn btn-secondary m-1">Back to List</a>
</div>

Views/BioSamples/Edit.cshtml
@model Intex.BioSamples

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit BioSample Entry</h1>

@*Page and form to allow a user to edit a specific database entry*@

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="BioSampleId" />
            <div class="form-group">
                <label asp-for="RackNumber" class="control-label"></label>
                <input asp-for="RackNumber" class="form-control" />
                <span asp-validation-for="RackNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BagNumber" class="control-label"></label>
                <input asp-for="BagNumber" class="form-control" />
                <span asp-validation-for="BagNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LowPairNs" class="control-label"></label>
                <input asp-for="LowPairNs" class="form-control" />
                <span asp-validation-for="LowPairNs" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HighPairNs" class="control-label"></label>
                <input asp-for="HighPairNs" class="form-control" />
                <span asp-validation-for="HighPairNs" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BurialLocationNs" class="control-label"></label>
                <input asp-for="BurialLocationNs" class="form-control" />
                <span asp-validation-for="BurialLocationNs" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LowPairEw" class="control-label"></label>
                <input asp-for="LowPairEw" class="form-control" />
                <span asp-validation-for="LowPairEw" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HighPairEw" class="control-label"></label>
                <input asp-for="HighPairEw" class="form-control" />
                <span asp-validation-for="HighPairEw" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BurialLocationEw" class="control-label"></label>
                <input asp-for="BurialLocationEw" class="form-control" />
                <span asp-validation-for="BurialLocationEw" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BurialSubplot" class="control-label"></label>
                <input asp-for="BurialSubplot" class="form-control" />
                <span asp-validation-for="BurialSubplot" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BurialNumber" class="control-label"></label>
                <input asp-for="BurialNumber" class="form-control" />
                <span asp-validation-for="BurialNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PreviouslySampled" class="control-label"></label>
                <input asp-for="PreviouslySampled" class="form-control" />
                <span asp-validation-for="PreviouslySampled" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Notes" class="control-label"></label>
                <input asp-for="Notes" class="form-control" />
                <span asp-validation-for="Notes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Initials" class="control-label"></label>
                <input asp-for="Initials" class="form-control" />
                <span asp-validation-for="Initials" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BurialId" class="control-label"></label>
                <select asp-for="BurialId" class="form-control" asp-items="ViewBag.BurialId"></select>
                <span asp-validation-for="BurialId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-secondary m-1">Back to List</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/BioSamples/Index.cshtml
@model IndexViewModel
@inject SignInManager<IdentityUser> signInManager;

@{
    ViewData["Title"] = "Bio Samples";
    ViewData["Description"] = "Excavated mummies that have been brought back to BYU";

    Layout = "~/Views/Shared/_Layout.cshtml";
}

@*Display a sexy masthead image to welcome the user to the page*@
@section masthead{
    <partial name="_BigOlPicturesPartial" />
}

@*Add in these scripts to allow filter box to work*@
@section header{
    <script src="https://code.jquery.com/jquery-2.2.4.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            $("#demo").on("keyup", function () {
                var value = $(this).val().toLowerCase();
                $("#test tr").filter(function () {
                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
            });
        });
    </script>
}
<br />

@*Search box for filtering, table to display all information*@
<div class="container">
    <h5>Quick filter for data on this page</h5>
    <input class="form-control" id="demo" type="text" placeholder="Enter your search term here...">
    <br />

    <div class="card">
        <div class="card-header" id="headingOne">
            <h5 class="mb-0">
                <a class="btn" asp-area="" asp-controller="BioSamples" asp-action="AllData">You can also filter on all Bio Sample data by clicking here</a>
            </h5>
        </div>
    </div>
    <br />

    @*Allow ability to add new entry for admins and researchers*@
    @if (signInManager.IsSignedIn(User) && (User.IsInRole("Admin") || (User.IsInRole("Researcher"))))
    {
        <a class="btn btn-egyptianblue m-1" asp-action="Create">Add New Entry</a>
        <br />
    }
    <br />

    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Rack Number</th>
                <th>Burial Subplot</th>
                <th>Burial Number</th>
                <th>Date</th>
                <th></th>
            </tr>
        </thead>
        <tbody id="test">
            @foreach (var item in Model.BioSamples)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.RackNumber)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.BurialSubplot)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.BurialNumber)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Date)
                    </td>
                    <td>
                        @if (signInManager.IsSignedIn(User) && (User.IsInRole("Admin") || (User.IsInRole("Researcher"))))
                        {
                            <a asp-action="Edit" asp-route-id="@item.BioSampleId" class="btn btn-secondary m-1" style="width: 80px">Edit</a>
                        }

                        <a asp-action="Details" asp-route-id="@item.BioSampleId" class="btn btn-brownsugar m-1" style="width: 80px">Details</a>
                        @if (signInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                        {
                            <a asp-action="Delete" asp-route-id="@item.BioSampleId" class="btn btn-cedarchest m-1" style="width: 80px">Delete</a>
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

    <div class="text-center">
        <div page-model="@Model.PagingInfo"
             page-classes-enabled="true"
             page-class="btn"
             page-class-normal="btn-outline-dark"
             page-class-selected="btn-egyptianblue"
             class="btn-group pull-right m-1"></div>
    </div>